//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tofix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewResponse()
        {
            this.ReactionEmojis = new HashSet<ReactionEmoji>();
        }
    
        public int ID { get; set; }
        public Nullable<int> reviewID { get; set; }
        public string userID { get; set; }
        public string Response { get; set; }
        public string BodyText { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual UserData UserData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReactionEmoji> ReactionEmojis { get; set; }
    }
}
